### PR TITLE
General Implement Parse RR

### PR DESCRIPTION
**Pull request by chenhw2**

### CODE REVIEW

**Comment by chenhw2** [comment]
Can due with any dns.Type, like (SOA, NS, ANY).

Reference https://github.com/pforemski/dingo/blob/master/dingo.go
func getrr(grr GRR) dns.RR

**Comment by fardog** [comment]
ah cool, and thank you! far simpler than what I had! however it looks like tests are failing; would it be possible to have those updated?

**Comment by chenhw2** [comment]
Fixed provider_test.go

**Comment by fardog** [comment]
thank you! i'll be testing this out in my environment, and will merge/release as a minor version bump in the next few days.

**Pull request merged**
